/*

 MAP_DATA.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : P:\uranus\gfx\pacman-tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_dataWidth 20
#define map_dataHeight 18
#define map_dataBank 0

extern unsigned char map_data[];

/* End of MAP_DATA.H */
